window.App = Ember.Application.create();
App.ApplicationAdapter = DS.FixtureAdapter.extend();

App.Store = DS.Store.extend({
	revision: 11,
	adapter: 'DS.FixtureAdapter'
});

//Routers
App.Router.map(function() {
	this.resource('draft', {path:'draft/:draft_id'}, function(){
		this.resource('draftPick', {path:'draftPick/:draftPick_id'});
	});
});

//Controllers
App.NavBarController = Ember.ObjectController.extend({

	drafts: function() {
		return this.store.find('draft');
	}.property(),

});

//Models
App.Draft = DS.Model.extend({
	name: DS.attr('string'),
	draftNumber: DS.attr('number'),
	draftDate: DS.attr('date'),
	draftPlayer: DS.belongsTo('player'),
	players: DS.hasMany('player', { async: true }),
	draftPicks: DS.hasMany('draftPick', { async: true }),
});

App.Player = DS.Model.extend({
	name: DS.attr('name')
});

App.DraftPick = DS.Model.extend({
	packEdition: DS.attr('string'),
	packNumber: DS.attr('number'),
	pickNumber: DS.attr('number'),
	cards: DS.hasMany('card', { async: true }),
	playerPick: DS.belongsTo('card'),
	reviewerPick: DS.belongsTo('card')
});

App.Card = DS.Model.extend({
	edition: DS.attr('string'),
	name: DS.attr('string'),
	imgUrl: DS.attr('string')
});


//Fixtures
App.Draft.FIXTURES = [
	{
		id: 1,
		name: 'Test Draft 1',
		draftNumber: 4407352,
		draftDate: '9/30/2012 8:31:05PM',
		draftPlayer: 1,
		players: [1,2,3,4,5,6,7,8],
		draftPicks: [1,	2,	3,	4,	5,	6,	7,	8,	9,	10,	11,	12,	13,	14,	15,	16,	17,	18,	19,	20,	21,	22,	23,	24,	25,	26,	27,	28,	29,	30,	31,	32,	33,	34,	35,	36,	37,	38,	39,	40,	41,	42,	43,	44]
	},
	{
		id: 2,
		name: 'Test Draft 2',
		draftNumber: 4407352,
		draftDate: '9/30/2012 8:31:05PM',
		draftPlayer: 1,
		players: [1,2,3,4,5,6,7,8],
		draftPicks: [1,	2,	3,	4,	5,	6,	7,	8,	9,	10,	11,	12,	13,	14,	15,	16,	17,	18,	19,	20,	21,	22,	23,	24,	25,	26,	27,	28,	29,	30,	31,	32,	33,	34,	35,	36,	37,	38,	39,	40,	41,	42,	43,	44]
	}


];

App.Player.FIXTURES = [

	{id: 1, name:'TomM'},
	{id: 2, name:'serenity_now'},
	{id: 3, name:'dolenin'},
	{id: 4, name:'Diamondeye'},
	{id: 5, name:'Emp87'},
	{id: 6, name:'Cardweaver'},
	{id: 7, name:'Xaturanga'},
	{id: 8, name:'Hilbs'}

];

App.DraftPick.FIXTURES = [

{id: 1, category: 'M12', packNumber:  1, pickNumber:  1, cards: [146,194,24,119,144,193,107,246,175,159,98,27,244,234,261], playerPick: 146, reviewerPick: null},
{id: 2, category: 'M12', packNumber:  1, pickNumber:  2, cards: [174,5,138,186,173,139,132,120,50,17,92,275,151,270], playerPick: 5, reviewerPick: null},
{id: 3, category: 'M12', packNumber:  1, pickNumber:  3, cards: [95,46,213,169,202,59,260,232,117,231,129,84,13], playerPick: 46, reviewerPick: null},
{id: 4, category: 'M12', packNumber:  1, pickNumber:  4, cards: [30,23,163,68,188,96,121,2,276,34,218,187], playerPick: 96, reviewerPick: null},
{id: 5, category: 'M12', packNumber:  1, pickNumber:  5, cards: [264,198,220,62,9,131,150,154,36,161,101], playerPick: 198, reviewerPick: null},
{id: 6, category: 'M12', packNumber:  1, pickNumber:  6, cards: [267,70,203,93,214,221,48,180,87,190], playerPick: 70, reviewerPick: null},
{id: 7, category: 'M12', packNumber:  1, pickNumber:  7, cards: [26,21,116,125,128,143,83,235,257], playerPick: 125, reviewerPick: null},
{id: 8, category: 'M12', packNumber:  1, pickNumber:  8, cards: [230,217,4,162,185,86,51,71], playerPick: 230, reviewerPick: null},
{id: 9, category: 'M12', packNumber:  1, pickNumber:  9, cards: [144,193,246,175,27,234,261], playerPick: 246, reviewerPick: null},
{id: 10, category: 'M12', packNumber:  1, pickNumber: 10, cards: [174,139,132,120,151,270], playerPick: 139, reviewerPick: null},
{id: 11, category: 'M12', packNumber:  1, pickNumber: 11, cards: [95,169,59,231,129], playerPick: 169, reviewerPick: null},
{id: 12, category: 'M12', packNumber:  1, pickNumber: 12, cards: [30,68,2,187], playerPick: 2, reviewerPick: null},
{id: 13, category: 'M12', packNumber:  1, pickNumber: 13, cards: [220,154,36], playerPick: 220, reviewerPick: null},
{id: 14, category: 'M12', packNumber:  1, pickNumber: 14, cards: [87,190], playerPick: 87, reviewerPick: null},
{id: 15, category: 'UZ', packNumber:  1, pickNumber: 15, cards: [235], playerPick: 235, reviewerPick: null},
{id: 16, category: 'UZ', packNumber:  2, pickNumber:  1, cards: [183,135,97,268,147,273,164,113,110,277,171,63,182,204,181], playerPick: 273, reviewerPick: null},
{id: 17, category: 'UZ', packNumber:  2, pickNumber:  2, cards: [37,249,60,105,75,259,109,65,94,28,252,127,64,66], playerPick: 249, reviewerPick: null},
{id: 18, category: 'UZ', packNumber:  2, pickNumber:  3, cards: [263,149,19,40,272,158,39,168,12,8,140,79,6], playerPick: 149, reviewerPick: null},
{id: 19, category: 'UZ', packNumber:  2, pickNumber:  4, cards: [157,172,3,134,209,14,179,165,208,114,32,115], playerPick: 134, reviewerPick: null},
{id: 20, category: 'UZ', packNumber:  2, pickNumber:  5, cards: [118,237,54,16,178,82,57,76,274,239,33], playerPick: 54, reviewerPick: null},
{id: 21, category: 'UZ', packNumber:  2, pickNumber:  6, cards: [224,18,72,266,85,197,58,233,44,123], playerPick: 233, reviewerPick: null},
{id: 22, category: 'UZ', packNumber:  2, pickNumber:  7, cards: [212,133,81,80,1,192,153,184,201], playerPick: 133, reviewerPick: null},
{id: 23, category: 'UZ', packNumber:  2, pickNumber:  8, cards: [53,20,141,156,122,90,108,170], playerPick: 122, reviewerPick: null},
{id: 24, category: 'UZ', packNumber:  2, pickNumber:  9, cards: [135,268,110,277,171,182,204], playerPick: 110, reviewerPick: null},
{id: 25, category: 'UZ', packNumber:  2, pickNumber: 10, cards: [37,60,75,259,65,66], playerPick: 75, reviewerPick: null},
{id: 26, category: 'UZ', packNumber:  2, pickNumber: 11, cards: [40,39,168,79,6], playerPick: 168, reviewerPick: null},
{id: 27, category: 'UZ', packNumber:  2, pickNumber: 12, cards: [157,179,114,115], playerPick: 115, reviewerPick: null},
{id: 28, category: 'UZ', packNumber:  2, pickNumber: 13, cards: [237,76,33], playerPick: 33, reviewerPick: null},
{id: 29, category: 'UZ', packNumber:  2, pickNumber: 14, cards: [224,72], playerPick: 72, reviewerPick: null},
{id: 30, category: 'WWK', packNumber:  2, pickNumber: 15, cards: [81], playerPick: 81, reviewerPick: null},
{id: 31, category: 'WWK', packNumber:  3, pickNumber:  1, cards: [215,243,124,29,226,167,191,236,49,100,35,241,225,55,196], playerPick: 226, reviewerPick: null},
{id: 32, category: 'WWK', packNumber:  3, pickNumber:  2, cards: [269,238,248,211,195,160,31,166,200,61,25,112,73,152], playerPick: 238, reviewerPick: null},
{id: 33, category: 'WWK', packNumber:  3, pickNumber:  3, cards: [148,52,99,91,199,207,256,111,228,22,74,258,176], playerPick: 199, reviewerPick: null},
{id: 34, category: 'WWK', packNumber:  3, pickNumber:  4, cards: [69,104,89,262,45,245,145,42,11,219,206,189], playerPick: 45, reviewerPick: null},
{id: 35, category: 'WWK', packNumber:  3, pickNumber:  5, cards: [126,253,102,222,247,7,271,155,254,78,130], playerPick: 253, reviewerPick: null},
{id: 36, category: 'WWK', packNumber:  3, pickNumber:  6, cards: [67,56,47,216,223,242,10,250,77,15], playerPick: 216, reviewerPick: null},
{id: 37, category: 'WWK', packNumber:  3, pickNumber:  7, cards: [229,142,137,210,136,103,88,255,177], playerPick: 210, reviewerPick: null},
{id: 38, category: 'WWK', packNumber:  3, pickNumber:  8, cards: [38,205,240,227,43,251,106,265], playerPick: 265, reviewerPick: null},
{id: 39, category: 'WWK', packNumber:  3, pickNumber:  9, cards: [236,49,100,35,241,225,55], playerPick: 100, reviewerPick: null},
{id: 40, category: 'WWK', packNumber:  3, pickNumber: 10, cards: [211,31,200,61,112,73], playerPick: 73, reviewerPick: null},
{id: 41, category: 'WWK', packNumber:  3, pickNumber: 11, cards: [91,207,228,22,176], playerPick: 207, reviewerPick: null},
{id: 42, category: 'WWK', packNumber:  3, pickNumber: 12, cards: [69,145,11,219], playerPick: 219, reviewerPick: null},
{id: 43, category: 'WWK', packNumber:  3, pickNumber: 13, cards: [155,254,130], playerPick: 155, reviewerPick: null},
{id: 44, category: 'WWK', packNumber:  3, pickNumber: 14, cards: [47,10], playerPick: 10, reviewerPick: null},

];

App.Card.FIXTURES = [


{id: 1, name: 'Absorb', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Absorb.jpg'},
{id: 2, name: 'Academy Ruins', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Academy_Ruins.jpg'},
{id: 3, name: 'Acidic Slime', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Acidic_Slime.jpg'},
{id: 4, name: 'Adarkar Wastes', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Adarkar_Wastes.jpg'},
{id: 5, name: 'Aeon Chronicler', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Aeon_Chronicler.jpg'},
{id: 6, name: 'Akroma, Angel of Fury', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Akroma,_Angel_of_Fury.jpg'},
{id: 7, name: 'Akroma, Angel of Wrath', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Akroma,_Angel_of_Wrath.jpg'},
{id: 8, name: 'Akroma\'s Vengeance', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Akroma\s_Vengeance.jpg'},
{id: 9, name: 'All Is Dust', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//All_Is_Dust.jpg'},
{id: 10, name: 'All Suns\' Dawn', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//All_Suns\_Dawn.jpg'},
{id: 11, name: 'Angel of Despair', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Angel_of_Despair.jpg'},
{id: 12, name: 'Ankh of Mishra', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Ankh_of_Mishra.jpg'},
{id: 13, name: 'Arbor Elf', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Arbor_Elf.jpg'},
{id: 14, name: 'Avacyn, Angel of Hope', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Avacyn,_Angel_of_Hope.jpg'},
{id: 15, name: 'Avalanche Riders', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Avalanche_Riders.jpg'},
{id: 16, name: 'Badlands', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Badlands.jpg'},
{id: 17, name: 'Bant Charm', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Bant_Charm.jpg'},
{id: 18, name: 'Birthing Pod', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Birthing_Pod.jpg'},
{id: 19, name: 'Bitterblossom', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Bitterblossom.jpg'},
{id: 20, name: 'Black Vise', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Black_Vise.jpg'},
{id: 21, name: 'Blistering Firecat', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Blistering_Firecat.jpg'},
{id: 22, name: 'Blood Knight', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Blood_Knight.jpg'},
{id: 23, name: 'Bloodghast', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Bloodghast.jpg'},
{id: 24, name: 'Bloodgift Demon', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Bloodgift_Demon.jpg'},
{id: 25, name: 'Blue Elemental Blast', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Blue_Elemental_Blast.jpg'},
{id: 26, name: 'Braids, Cabal Minion', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Braids,_Cabal_Minion.jpg'},
{id: 27, name: 'Brain Freeze', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Brain_Freeze.jpg'},
{id: 28, name: 'Brainstorm', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Brainstorm.jpg'},
{id: 29, name: 'Brimstone Volley', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Brimstone_Volley.jpg'},
{id: 30, name: 'Brine Elemental', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Brine_Elemental.jpg'},
{id: 31, name: 'Broodmate Dragon', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Broodmate_Dragon.jpg'},
{id: 32, name: 'Buried Alive', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Buried_Alive.jpg'},
{id: 33, name: 'Burning of Xinye', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Burning_of_Xinye.jpg'},
{id: 34, name: 'Calciderm', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Calciderm.jpg'},
{id: 35, name: 'Call the Skybreaker', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Call_the_Skybreaker.jpg'},
{id: 36, name: 'Carnophage', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Carnophage.jpg'},
{id: 37, name: 'Cataclysm', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Cataclysm.jpg'},
{id: 38, name: 'Catastrophe', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Catastrophe.jpg'},
{id: 39, name: 'Cathedral of War', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Cathedral_of_War.jpg'},
{id: 40, name: 'Chaos Warp', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Chaos_Warp.jpg'},
{id: 41, name: 'Clean Card', edition: '', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Clean_Card.jpg'},
{id: 42, name: 'Clifftop Retreat', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Clifftop_Retreat.jpg'},
{id: 43, name: 'Cloudgoat Ranger', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Cloudgoat_Ranger.jpg'},
{id: 44, name: 'Cloudthresher', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Cloudthresher.jpg'},
{id: 45, name: 'Coldsteel Heart', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Coldsteel_Heart.jpg'},
{id: 46, name: 'Compulsive Research', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Compulsive_Research.jpg'},
{id: 47, name: 'Dark Ritual', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Dark_Ritual.jpg'},
{id: 48, name: 'Daybreak Ranger', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Daybreak_Ranger.jpg'},
{id: 49, name: 'Deathmark', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Deathmark.jpg'},
{id: 50, name: 'Decree of Justice', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Decree_of_Justice.jpg'},
{id: 51, name: 'Delver of Secrets', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Delver_of_Secrets.jpg'},
{id: 52, name: 'Demonic Tutor', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Demonic_Tutor.jpg'},
{id: 53, name: 'Devastating Dreams', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Devastating_Dreams.jpg'},
{id: 54, name: 'Devoted Druid', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Devoted_Druid.jpg'},
{id: 55, name: 'Disenchant', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Disenchant.jpg'},
{id: 56, name: 'Dismiss', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Dismiss.jpg'},
{id: 57, name: 'Dragonskull Summit', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Dragonskull_Summit.jpg'},
{id: 58, name: 'Drogskol Reaver', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Drogskol_Reaver.jpg'},
{id: 59, name: 'Dryad Militant', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Dryad_Militant.jpg'},
{id: 60, name: 'Duress', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Duress.jpg'},
{id: 61, name: 'Earthquake', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Earthquake.jpg'},
{id: 62, name: 'Edric, Spymaster of Trest', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Edric,_Spymaster_of_Trest.jpg'},
{id: 63, name: 'Ember Hauler', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Ember_Hauler.jpg'},
{id: 64, name: 'Emeria Angel', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Emeria_Angel.jpg'},
{id: 65, name: 'Empty the Warrens', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Empty_the_Warrens.jpg'},
{id: 66, name: 'Enclave Cryptologist', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Enclave_Cryptologist.jpg'},
{id: 67, name: 'Enlightened Tutor', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Enlightened_Tutor.jpg'},
{id: 68, name: 'Epochrasite', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Epochrasite.jpg'},
{id: 69, name: 'Eternal Dragon', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Eternal_Dragon.jpg'},
{id: 70, name: 'Eternal Witness', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Eternal_Witness.jpg'},
{id: 71, name: 'Ethersworn Canonist', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Ethersworn_Canonist.jpg'},
{id: 72, name: 'Everflowing Chalice', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Everflowing_Chalice.jpg'},
{id: 73, name: 'Exhume', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Exhume.jpg'},
{id: 74, name: 'Fathom Seer', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Fathom_Seer.jpg'},
{id: 75, name: 'Fauna Shaman', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Fauna_Shaman.jpg'},
{id: 76, name: 'Firemane Angel', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Firemane_Angel.jpg'},
{id: 77, name: 'Forbid', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Forbid.jpg'},
{id: 78, name: 'Frantic Search', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Frantic_Search.jpg'},
{id: 79, name: 'Gathan Raiders', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Gathan_Raiders.jpg'},
{id: 80, name: 'Genesis', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Genesis.jpg'},
{id: 81, name: 'Genju of the Spires', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Genju_of_the_Spires.jpg'},
{id: 82, name: 'Gifts Ungiven', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Gifts_Ungiven.jpg'},
{id: 83, name: 'Gloom Surgeon', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Gloom_Surgeon.jpg'},
{id: 84, name: 'Glorious Anthem', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Glorious_Anthem.jpg'},
{id: 85, name: 'Goblin Legionnaire', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Goblin_Legionnaire.jpg'},
{id: 86, name: 'Goblin Trenches', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Goblin_Trenches.jpg'},
{id: 87, name: 'Goblin Welder', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Goblin_Welder.jpg'},
{id: 88, name: 'Great Sable Stag', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Great_Sable_Stag.jpg'},
{id: 89, name: 'Guul Draz Assassin', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Guul_Draz_Assassin.jpg'},
{id: 90, name: 'Headhunter', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Headhunter.jpg'},
{id: 91, name: 'Heartbeat of Spring', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Heartbeat_of_Spring.jpg'},
{id: 92, name: 'Hero of Oxid Ridge', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Hero_of_Oxid_Ridge.jpg'},
{id: 93, name: 'Hex Parasite', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Hex_Parasite.jpg'},
{id: 94, name: 'Hinterland Harbor', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Hinterland_Harbor.jpg'},
{id: 95, name: 'Honor of the Pure', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Honor_of_the_Pure.jpg'},
{id: 96, name: 'Huntmaster of the Fells', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Huntmaster_of_the_Fells.jpg'},
{id: 97, name: 'Hymn to Tourach', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Hymn_to_Tourach.jpg'},
{id: 98, name: 'Impulse', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Impulse.jpg'},
{id: 99, name: 'Inferno Titan', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Inferno_Titan.jpg'},
{id: 100, name: 'Ingot Chewer', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Ingot_Chewer.jpg'},
{id: 101, name: 'Innocent Blood', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Innocent_Blood.jpg'},
{id: 102, name: 'Inquisition of Kozilek', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Inquisition_of_Kozilek.jpg'},
{id: 103, name: 'Isolated Chapel', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Isolated_Chapel.jpg'},
{id: 104, name: 'Jace Beleren', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Jace_Beleren.jpg'},
{id: 105, name: 'Jackal Pup', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Jackal_Pup.jpg'},
{id: 106, name: 'Journey to Nowhere', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Journey_to_Nowhere.jpg'},
{id: 107, name: 'Karakas', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Karakas.jpg'},
{id: 108, name: 'Kird Ape', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Kird_Ape.jpg'},
{id: 109, name: 'Kitchen Finks', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Kitchen_Finks.jpg'},
{id: 110, name: 'Krosan Grip', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Krosan_Grip.jpg'},
{id: 111, name: 'Lake of the Dead', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Lake_of_the_Dead.jpg'},
{id: 112, name: 'Laquatus\'s Champion', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Laquatus\s_Champion.jpg'},
{id: 113, name: 'Lightning Helix', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Lightning_Helix.jpg'},
{id: 114, name: 'Liliana of the Dark Realms', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Liliana_of_the_Dark_Realms.jpg'},
{id: 115, name: 'Looter il-Kor', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Looter_il-Kor.jpg'},
{id: 116, name: 'Lotus Bloom', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Lotus_Bloom.jpg'},
{id: 117, name: 'Loxodon Hierarch', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Loxodon_Hierarch.jpg'},
{id: 118, name: 'Loyal Cathar', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Loyal_Cathar.jpg'},
{id: 119, name: 'Magma Jet', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Magma_Jet.jpg'},
{id: 120, name: 'Manriki-Gusari', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Manriki-Gusari.jpg'},
{id: 121, name: 'Masticore', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Masticore.jpg'},
{id: 122, name: 'Meloku the Clouded Mirror', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Meloku_the_Clouded_Mirror.jpg'},
{id: 123, name: 'Memory Lapse', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Memory_Lapse.jpg'},
{id: 124, name: 'Mesmeric Fiend', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Mesmeric_Fiend.jpg'},
{id: 125, name: 'Mimic Vat', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Mimic_Vat.jpg'},
{id: 126, name: 'Mirran Crusader', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Mirran_Crusader.jpg'},
{id: 127, name: 'Mirror Entity', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Mirror_Entity.jpg'},
{id: 128, name: 'Mishra\'s Factory', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Mishra\s_Factory.jpg'},
{id: 129, name: 'Moldervine Cloak', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Moldervine_Cloak.jpg'},
{id: 130, name: 'Molten Rain', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Molten_Rain.jpg'},
{id: 131, name: 'Momentary Blink', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Momentary_Blink.jpg'},
{id: 132, name: 'Mortify', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Mortify.jpg'},
{id: 133, name: 'Mulldrifter', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Mulldrifter.jpg'},
{id: 134, name: 'Myr Battlesphere', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Myr_Battlesphere.jpg'},
{id: 135, name: 'Mystical Tutor', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Mystical_Tutor.jpg'},
{id: 136, name: 'Nantuko Shade', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Nantuko_Shade.jpg'},
{id: 137, name: 'Natural Order', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Natural_Order.jpg'},
{id: 138, name: 'Necropotence', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Necropotence.jpg'},
{id: 139, name: 'Nevinyrral\'s Disk', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Nevinyrral\s_Disk.jpg'},
{id: 140, name: 'Nezumi Graverobber', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Nezumi_Graverobber.jpg'},
{id: 141, name: 'Nicol Bolas, Planeswalker', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Nicol_Bolas,_Planeswalker.jpg'},
{id: 142, name: 'Night\'s Whisper', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Night\s_Whisper.jpg'},
{id: 143, name: 'Ninja of the Deep Hours', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Ninja_of_the_Deep_Hours.jpg'},
{id: 144, name: 'Nostalgic Dreams', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Nostalgic_Dreams.jpg'},
{id: 145, name: 'Nucklavee', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Nucklavee.jpg'},
{id: 146, name: 'Oblivion Ring', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Oblivion_Ring.jpg'},
{id: 147, name: 'Ohran Viper', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Ohran_Viper.jpg'},
{id: 148, name: 'Old Man of the Sea', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Old_Man_of_the_Sea.jpg'},
{id: 149, name: 'Opposition', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Opposition.jpg'},
{id: 150, name: 'Opt', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Opt.jpg'},
{id: 151, name: 'Pact of Negation', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Pact_of_Negation.jpg'},
{id: 152, name: 'Paladin en-Vec', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Paladin_en-Vec.jpg'},
{id: 153, name: 'Palinchron', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Palinchron.jpg'},
{id: 154, name: 'Persecute', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Persecute.jpg'},
{id: 155, name: 'Phantom Centaur', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Phantom_Centaur.jpg'},
{id: 156, name: 'Phyrexian Processor', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Phyrexian_Processor.jpg'},
{id: 157, name: 'Phyrexian Rager', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Phyrexian_Rager.jpg'},
{id: 158, name: 'Phyrexian Revoker', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Phyrexian_Revoker.jpg'},
{id: 159, name: 'Pillage', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Pillage.jpg'},
{id: 160, name: 'Plateau', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Plateau.jpg'},
{id: 161, name: 'Plated Geopede', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Plated_Geopede.jpg'},
{id: 162, name: 'Platinum Angel', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Platinum_Angel.jpg'},
{id: 163, name: 'Plow Under', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Plow_Under.jpg'},
{id: 164, name: 'Polluted Delta', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Polluted_Delta.jpg'},
{id: 165, name: 'Ponder', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Ponder.jpg'},
{id: 166, name: 'Powder Keg', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Powder_Keg.jpg'},
{id: 167, name: 'Precursor Golem', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Precursor_Golem.jpg'},
{id: 168, name: 'Prophetic Bolt', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Prophetic_Bolt.jpg'},
{id: 169, name: 'Pulse of the Forge', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Pulse_of_the_Forge.jpg'},
{id: 170, name: 'Putrid Imp', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Putrid_Imp.jpg'},
{id: 171, name: 'Putrid Leech', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Putrid_Leech.jpg'},
{id: 172, name: 'Pyrokinesis', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Pyrokinesis.jpg'},
{id: 173, name: 'Rancor', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Rancor.jpg'},
{id: 174, name: 'Ranger of Eos', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Ranger_of_Eos.jpg'},
{id: 175, name: 'Ratchet Bomb', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Ratchet_Bomb.jpg'},
{id: 176, name: 'Ravenous Baboons', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Ravenous_Baboons.jpg'},
{id: 177, name: 'Ray of Revelation', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Ray_of_Revelation.jpg'},
{id: 178, name: 'Realm Razer', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Realm_Razer.jpg'},
{id: 179, name: 'Regrowth', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Regrowth.jpg'},
{id: 180, name: 'Renewed Faith', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Renewed_Faith.jpg'},
{id: 181, name: 'Repeal', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Repeal.jpg'},
{id: 182, name: 'Restock', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Restock.jpg'},
{id: 183, name: 'Restoration Angel', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Restoration_Angel.jpg'},
{id: 184, name: 'Rolling Earthquake', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Rolling_Earthquake.jpg'},
{id: 185, name: 'Rootbound Crag', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Rootbound_Crag.jpg'},
{id: 186, name: 'Rorix Bladewing', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Rorix_Bladewing.jpg'},
{id: 187, name: 'Rude Awakening', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Rude_Awakening.jpg'},
{id: 188, name: 'Sacred Foundry', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Sacred_Foundry.jpg'},
{id: 189, name: 'Sakura-Tribe Elder', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Sakura-Tribe_Elder.jpg'},
{id: 190, name: 'Sarcomancy', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Sarcomancy.jpg'},
{id: 191, name: 'Savannah', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Savannah.jpg'},
{id: 192, name: 'Seal of Primordium', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Seal_of_Primordium.jpg'},
{id: 193, name: 'Sensei\'s Divining Top', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Sensei\s_Divining_Top.jpg'},
{id: 194, name: 'Serendib Efreet', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Serendib_Efreet.jpg'},
{id: 195, name: 'Shrine of Burning Rage', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Shrine_of_Burning_Rage.jpg'},
{id: 196, name: 'Silver Knight', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Silver_Knight.jpg'},
{id: 197, name: 'Slaughter Pact', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Slaughter_Pact.jpg'},
{id: 198, name: 'Snapcaster Mage', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Snapcaster_Mage.jpg'},
{id: 199, name: 'Solemn Simulacrum', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Solemn_Simulacrum.jpg'},
{id: 200, name: 'Sorin\'s Thirst', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Sorin\s_Thirst.jpg'},
{id: 201, name: 'Spell Pierce', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Spell_Pierce.jpg'},
{id: 202, name: 'Sphere of the Suns', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Sphere_of_the_Suns.jpg'},
{id: 203, name: 'Sphinx of the Steel Wind', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Sphinx_of_the_Steel_Wind.jpg'},
{id: 204, name: 'Spikeshot Elder', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Spikeshot_Elder.jpg'},
{id: 205, name: 'Spiritmonger', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Spiritmonger.jpg'},
{id: 206, name: 'Staggershock', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Staggershock.jpg'},
{id: 207, name: 'Steam Vents', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Steam_Vents.jpg'},
{id: 208, name: 'Stifle', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Stifle.jpg'},
{id: 209, name: 'Stirring Wildwood', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Stirring_Wildwood.jpg'},
{id: 210, name: 'Stomping Ground', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Stomping_Ground.jpg'},
{id: 211, name: 'Stormblood Berserker', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Stormblood_Berserker.jpg'},
{id: 212, name: 'Student of Warfare', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Student_of_Warfare.jpg'},
{id: 213, name: 'Stupor', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Stupor.jpg'},
{id: 214, name: 'Sulfur Falls', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Sulfur_Falls.jpg'},
{id: 215, name: 'Sun Titan', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Sun_Titan.jpg'},
{id: 216, name: 'Sundering Titan', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Sundering_Titan.jpg'},
{id: 217, name: 'Taiga', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Taiga.jpg'},
{id: 218, name: 'Talrand, Sky Summoner', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Talrand,_Sky_Summoner.jpg'},
{id: 219, name: 'Tandem Lookout', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tandem_Lookout.jpg'},
{id: 220, name: 'Tangle Wire', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tangle_Wire.jpg'},
{id: 221, name: 'Tattermunge Maniac', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tattermunge_Maniac.jpg'},
{id: 222, name: 'Taurean Mauler', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Taurean_Mauler.jpg'},
{id: 223, name: 'Tectonic Edge', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tectonic_Edge.jpg'},
{id: 224, name: 'Tendrils of Agony', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tendrils_of_Agony.jpg'},
{id: 225, name: 'Tendrils of Corruption', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tendrils_of_Corruption.jpg'},
{id: 226, name: 'Terastodon', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Terastodon.jpg'},
{id: 227, name: 'Terminus', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Terminus.jpg'},
{id: 228, name: 'Terror', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Terror.jpg'},
{id: 229, name: 'Thalia, Guardian of Thraben', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Thalia,_Guardian_of_Thraben.jpg'},
{id: 230, name: 'Thirst for Knowledge', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Thirst_for_Knowledge.jpg'},
{id: 231, name: 'Thornling', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Thornling.jpg'},
{id: 232, name: 'Thornscape Battlemage', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Thornscape_Battlemage.jpg'},
{id: 233, name: 'Thragtusk', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Thragtusk.jpg'},
{id: 234, name: 'Thunderscape Battlemage', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Thunderscape_Battlemage.jpg'},
{id: 235, name: 'Tibalt, the Fiend-Blooded', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tibalt,_the_Fiend-Blooded.jpg'},
{id: 236, name: 'Tidehollow Sculler', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tidehollow_Sculler.jpg'},
{id: 237, name: 'Tin Street Hooligan', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tin_Street_Hooligan.jpg'},
{id: 238, name: 'Tinker', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tinker.jpg'},
{id: 239, name: 'Tithe', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tithe.jpg'},
{id: 240, name: 'Tolaria West', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tolaria_West.jpg'},
{id: 241, name: 'Tombstalker', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tombstalker.jpg'},
{id: 242, name: 'Tormod\'s Crypt', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tormod\s_Crypt.jpg'},
{id: 243, name: 'Tradewind Rider', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tradewind_Rider.jpg'},
{id: 244, name: 'Troll Ascetic', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Troll_Ascetic.jpg'},
{id: 245, name: 'Tropical Island', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Tropical_Island.jpg'},
{id: 246, name: 'Trygon Predator', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Trygon_Predator.jpg'},
{id: 247, name: 'Ulamog, the Infinite Gyre', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Ulamog,_the_Infinite_Gyre.jpg'},
{id: 248, name: 'Unburial Rites', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Unburial_Rites.jpg'},
{id: 249, name: 'Upheaval', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Upheaval.jpg'},
{id: 250, name: 'Urabrask the Hidden', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Urabrask_the_Hidden.jpg'},
{id: 251, name: 'Vampire Hexmage', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Vampire_Hexmage.jpg'},
{id: 252, name: 'Vampire Lacerator', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Vampire_Lacerator.jpg'},
{id: 253, name: 'Vesuvan Shapeshifter', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Vesuvan_Shapeshifter.jpg'},
{id: 254, name: 'Vexing Devil', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Vexing_Devil.jpg'},
{id: 255, name: 'Vines of Vastwood', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Vines_of_Vastwood.jpg'},
{id: 256, name: 'Void', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Void.jpg'},
{id: 257, name: 'Voidmage Prodigy', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Voidmage_Prodigy.jpg'},
{id: 258, name: 'Volcanic Hammer', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Volcanic_Hammer.jpg'},
{id: 259, name: 'Volcanic Island', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Volcanic_Island.jpg'},
{id: 260, name: 'Vulshok Refugee', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Vulshok_Refugee.jpg'},
{id: 261, name: 'Wake Thrasher', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Wake_Thrasher.jpg'},
{id: 262, name: 'Wall of Blossoms', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Wall_of_Blossoms.jpg'},
{id: 263, name: 'Wall of Omens', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Wall_of_Omens.jpg'},
{id: 264, name: 'Wall of Reverence', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Wall_of_Reverence.jpg'},
{id: 265, name: 'Wall of Roots', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Wall_of_Roots.jpg'},
{id: 266, name: 'Wasteland', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Wasteland.jpg'},
{id: 267, name: 'Weathered Wayfarer', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Weathered_Wayfarer.jpg'},
{id: 268, name: 'Wheel of Fortune', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Wheel_of_Fortune.jpg'},
{id: 269, name: 'Whipcorder', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Whipcorder.jpg'},
{id: 270, name: 'White Knight', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//White_Knight.jpg'},
{id: 271, name: 'Windbrisk Heights', edition: 'WWK', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Windbrisk_Heights.jpg'},
{id: 272, name: 'Wolfir Silverheart', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Wolfir_Silverheart.jpg'},
{id: 273, name: 'Worn Powerstone', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Worn_Powerstone.jpg'},
{id: 274, name: 'Worship', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Worship.jpg'},
{id: 275, name: 'Yavimaya Coast', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Yavimaya_Coast.jpg'},
{id: 276, name: 'Yeva, Nature\'s Herald', edition: 'M12', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Yeva,_Nature\s_Herald.jpg'},
{id: 277, name: 'Zombie Cutthroat', edition: 'UZ', imgUrl: 'http:////www.wizards.com//global//images//magic//general//Zombie_Cutthroat.jpg'}

];